// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: com_cliente.proto

package com_cliente

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Libro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Titulo      string `protobuf:"bytes,1,opt,name=Titulo,proto3" json:"Titulo,omitempty"`
	TotalChunks uint64 `protobuf:"varint,2,opt,name=TotalChunks,proto3" json:"TotalChunks,omitempty"`
	ChunkActual uint64 `protobuf:"varint,3,opt,name=ChunkActual,proto3" json:"ChunkActual,omitempty"`
	Chunk       []byte `protobuf:"bytes,4,opt,name=Chunk,proto3" json:"Chunk,omitempty"`
}

func (x *Libro) Reset() {
	*x = Libro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_cliente_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Libro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Libro) ProtoMessage() {}

func (x *Libro) ProtoReflect() protoreflect.Message {
	mi := &file_com_cliente_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Libro.ProtoReflect.Descriptor instead.
func (*Libro) Descriptor() ([]byte, []int) {
	return file_com_cliente_proto_rawDescGZIP(), []int{0}
}

func (x *Libro) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *Libro) GetTotalChunks() uint64 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *Libro) GetChunkActual() uint64 {
	if x != nil {
		return x.ChunkActual
	}
	return 0
}

func (x *Libro) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type EstadoSubida struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado bool   `protobuf:"varint,1,opt,name=Estado,proto3" json:"Estado,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *EstadoSubida) Reset() {
	*x = EstadoSubida{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_cliente_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstadoSubida) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoSubida) ProtoMessage() {}

func (x *EstadoSubida) ProtoReflect() protoreflect.Message {
	mi := &file_com_cliente_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoSubida.ProtoReflect.Descriptor instead.
func (*EstadoSubida) Descriptor() ([]byte, []int) {
	return file_com_cliente_proto_rawDescGZIP(), []int{1}
}

func (x *EstadoSubida) GetEstado() bool {
	if x != nil {
		return x.Estado
	}
	return false
}

func (x *EstadoSubida) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SolicitudChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Titulo string `protobuf:"bytes,1,opt,name=Titulo,proto3" json:"Titulo,omitempty"`
	NChunk uint64 `protobuf:"varint,2,opt,name=NChunk,proto3" json:"NChunk,omitempty"`
}

func (x *SolicitudChunk) Reset() {
	*x = SolicitudChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_cliente_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudChunk) ProtoMessage() {}

func (x *SolicitudChunk) ProtoReflect() protoreflect.Message {
	mi := &file_com_cliente_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudChunk.ProtoReflect.Descriptor instead.
func (*SolicitudChunk) Descriptor() ([]byte, []int) {
	return file_com_cliente_proto_rawDescGZIP(), []int{2}
}

func (x *SolicitudChunk) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *SolicitudChunk) GetNChunk() uint64 {
	if x != nil {
		return x.NChunk
	}
	return 0
}

type Chunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado bool   `protobuf:"varint,1,opt,name=Estado,proto3" json:"Estado,omitempty"` //para el caso de que no lo tenga el nodo
	Data   []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_cliente_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_com_cliente_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_com_cliente_proto_rawDescGZIP(), []int{3}
}

func (x *Chunk) GetEstado() bool {
	if x != nil {
		return x.Estado
	}
	return false
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_com_cliente_proto protoreflect.FileDescriptor

var file_com_cliente_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x6f, 0x6d, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65,
	0x22, 0x79, 0x0a, 0x05, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x69, 0x74,
	0x75, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x69, 0x74, 0x75, 0x6c,
	0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x41, 0x63, 0x74, 0x75,
	0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x41,
	0x63, 0x74, 0x75, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x38, 0x0a, 0x0c, 0x45,
	0x73, 0x74, 0x61, 0x64, 0x6f, 0x53, 0x75, 0x62, 0x69, 0x64, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x45,
	0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x45, 0x73, 0x74,
	0x61, 0x64, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x40, 0x0a, 0x0e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74,
	0x75, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x69, 0x74, 0x75, 0x6c,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x69, 0x74, 0x75, 0x6c, 0x6f, 0x12,
	0x16, 0x0a, 0x06, 0x4e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x4e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x33, 0x0a, 0x05, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x12, 0x16, 0x0a, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x32, 0x8b, 0x01, 0x0a,
	0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x3b,
	0x0a, 0x0a, 0x53, 0x75, 0x62, 0x69, 0x72, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x12, 0x12, 0x2e, 0x63,
	0x6f, 0x6d, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x2e, 0x4c, 0x69, 0x62, 0x72, 0x6f,
	0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x2e, 0x45,
	0x73, 0x74, 0x61, 0x64, 0x6f, 0x53, 0x75, 0x62, 0x69, 0x64, 0x61, 0x12, 0x3d, 0x0a, 0x0a, 0x50,
	0x65, 0x64, 0x69, 0x72, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x5f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75,
	0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x1a, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x5f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x65, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x3b,
	0x63, 0x6f, 0x6d, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_com_cliente_proto_rawDescOnce sync.Once
	file_com_cliente_proto_rawDescData = file_com_cliente_proto_rawDesc
)

func file_com_cliente_proto_rawDescGZIP() []byte {
	file_com_cliente_proto_rawDescOnce.Do(func() {
		file_com_cliente_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_cliente_proto_rawDescData)
	})
	return file_com_cliente_proto_rawDescData
}

var file_com_cliente_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_com_cliente_proto_goTypes = []interface{}{
	(*Libro)(nil),          // 0: com_cliente.Libro
	(*EstadoSubida)(nil),   // 1: com_cliente.EstadoSubida
	(*SolicitudChunk)(nil), // 2: com_cliente.SolicitudChunk
	(*Chunk)(nil),          // 3: com_cliente.Chunk
}
var file_com_cliente_proto_depIdxs = []int32{
	0, // 0: com_cliente.Interacciones.SubirLibro:input_type -> com_cliente.Libro
	2, // 1: com_cliente.Interacciones.PedirChunk:input_type -> com_cliente.SolicitudChunk
	1, // 2: com_cliente.Interacciones.SubirLibro:output_type -> com_cliente.EstadoSubida
	3, // 3: com_cliente.Interacciones.PedirChunk:output_type -> com_cliente.Chunk
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_com_cliente_proto_init() }
func file_com_cliente_proto_init() {
	if File_com_cliente_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_com_cliente_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Libro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_cliente_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstadoSubida); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_cliente_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolicitudChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_cliente_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_cliente_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_com_cliente_proto_goTypes,
		DependencyIndexes: file_com_cliente_proto_depIdxs,
		MessageInfos:      file_com_cliente_proto_msgTypes,
	}.Build()
	File_com_cliente_proto = out.File
	file_com_cliente_proto_rawDesc = nil
	file_com_cliente_proto_goTypes = nil
	file_com_cliente_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// InteraccionesClient is the client API for Interacciones service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InteraccionesClient interface {
	SubirLibro(ctx context.Context, in *Libro, opts ...grpc.CallOption) (*EstadoSubida, error)
	PedirChunk(ctx context.Context, in *SolicitudChunk, opts ...grpc.CallOption) (*Chunk, error)
}

type interaccionesClient struct {
	cc grpc.ClientConnInterface
}

func NewInteraccionesClient(cc grpc.ClientConnInterface) InteraccionesClient {
	return &interaccionesClient{cc}
}

func (c *interaccionesClient) SubirLibro(ctx context.Context, in *Libro, opts ...grpc.CallOption) (*EstadoSubida, error) {
	out := new(EstadoSubida)
	err := c.cc.Invoke(ctx, "/com_cliente.Interacciones/SubirLibro", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interaccionesClient) PedirChunk(ctx context.Context, in *SolicitudChunk, opts ...grpc.CallOption) (*Chunk, error) {
	out := new(Chunk)
	err := c.cc.Invoke(ctx, "/com_cliente.Interacciones/PedirChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteraccionesServer is the server API for Interacciones service.
type InteraccionesServer interface {
	SubirLibro(context.Context, *Libro) (*EstadoSubida, error)
	PedirChunk(context.Context, *SolicitudChunk) (*Chunk, error)
}

// UnimplementedInteraccionesServer can be embedded to have forward compatible implementations.
type UnimplementedInteraccionesServer struct {
}

func (*UnimplementedInteraccionesServer) SubirLibro(context.Context, *Libro) (*EstadoSubida, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubirLibro not implemented")
}
func (*UnimplementedInteraccionesServer) PedirChunk(context.Context, *SolicitudChunk) (*Chunk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PedirChunk not implemented")
}

func RegisterInteraccionesServer(s *grpc.Server, srv InteraccionesServer) {
	s.RegisterService(&_Interacciones_serviceDesc, srv)
}

func _Interacciones_SubirLibro_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Libro)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteraccionesServer).SubirLibro(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com_cliente.Interacciones/SubirLibro",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteraccionesServer).SubirLibro(ctx, req.(*Libro))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interacciones_PedirChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolicitudChunk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteraccionesServer).PedirChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com_cliente.Interacciones/PedirChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteraccionesServer).PedirChunk(ctx, req.(*SolicitudChunk))
	}
	return interceptor(ctx, in, info, handler)
}

var _Interacciones_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com_cliente.Interacciones",
	HandlerType: (*InteraccionesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubirLibro",
			Handler:    _Interacciones_SubirLibro_Handler,
		},
		{
			MethodName: "PedirChunk",
			Handler:    _Interacciones_PedirChunk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "com_cliente.proto",
}
