// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: com_datanode.proto

package com_datanode

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Disponibilidad struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado bool `protobuf:"varint,1,opt,name=Estado,proto3" json:"Estado,omitempty"`
}

func (x *Disponibilidad) Reset() {
	*x = Disponibilidad{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_datanode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Disponibilidad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disponibilidad) ProtoMessage() {}

func (x *Disponibilidad) ProtoReflect() protoreflect.Message {
	mi := &file_com_datanode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disponibilidad.ProtoReflect.Descriptor instead.
func (*Disponibilidad) Descriptor() ([]byte, []int) {
	return file_com_datanode_proto_rawDescGZIP(), []int{0}
}

func (x *Disponibilidad) GetEstado() bool {
	if x != nil {
		return x.Estado
	}
	return false
}

type Chunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Nombre string `protobuf:"bytes,2,opt,name=Nombre,proto3" json:"Nombre,omitempty"`
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_datanode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_com_datanode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_com_datanode_proto_rawDescGZIP(), []int{1}
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Chunk) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

type EstadoSubida struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado bool   `protobuf:"varint,1,opt,name=Estado,proto3" json:"Estado,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *EstadoSubida) Reset() {
	*x = EstadoSubida{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_datanode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstadoSubida) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoSubida) ProtoMessage() {}

func (x *EstadoSubida) ProtoReflect() protoreflect.Message {
	mi := &file_com_datanode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoSubida.ProtoReflect.Descriptor instead.
func (*EstadoSubida) Descriptor() ([]byte, []int) {
	return file_com_datanode_proto_rawDescGZIP(), []int{2}
}

func (x *EstadoSubida) GetEstado() bool {
	if x != nil {
		return x.Estado
	}
	return false
}

func (x *EstadoSubida) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_datanode_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_com_datanode_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_com_datanode_proto_rawDescGZIP(), []int{3}
}

type Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *Id) Reset() {
	*x = Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_datanode_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_com_datanode_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_com_datanode_proto_rawDescGZIP(), []int{4}
}

func (x *Id) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_com_datanode_proto protoreflect.FileDescriptor

var file_com_datanode_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x6f, 0x6d, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f,
	0x64, 0x65, 0x22, 0x28, 0x0a, 0x0e, 0x44, 0x69, 0x73, 0x70, 0x6f, 0x6e, 0x69, 0x62, 0x69, 0x6c,
	0x69, 0x64, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x33, 0x0a, 0x05,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x6d,
	0x62, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x6f, 0x6d, 0x62, 0x72,
	0x65, 0x22, 0x38, 0x0a, 0x0c, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x53, 0x75, 0x62, 0x69, 0x64,
	0x61, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x07, 0x0a, 0x05, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x14, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x32, 0xcc, 0x01, 0x0a, 0x0d, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x0a,
	0x44, 0x69, 0x73, 0x70, 0x6f, 0x6e, 0x69, 0x62, 0x6c, 0x65, 0x12, 0x13, 0x2e, 0x63, 0x6f, 0x6d,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x1c, 0x2e, 0x63, 0x6f, 0x6d, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x44,
	0x69, 0x73, 0x70, 0x6f, 0x6e, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x64, 0x61, 0x64, 0x12, 0x3f, 0x0a,
	0x0c, 0x53, 0x75, 0x62, 0x69, 0x72, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x6f, 0x12, 0x13, 0x2e,
	0x63, 0x6f, 0x6d, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x1a, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64,
	0x65, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x53, 0x75, 0x62, 0x69, 0x64, 0x61, 0x12, 0x39,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x49, 0x64, 0x1a, 0x1c, 0x2e, 0x63, 0x6f,
	0x6d, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x44, 0x69, 0x73, 0x70, 0x6f,
	0x6e, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x64, 0x61, 0x64, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x3b, 0x63,
	0x6f, 0x6d, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_com_datanode_proto_rawDescOnce sync.Once
	file_com_datanode_proto_rawDescData = file_com_datanode_proto_rawDesc
)

func file_com_datanode_proto_rawDescGZIP() []byte {
	file_com_datanode_proto_rawDescOnce.Do(func() {
		file_com_datanode_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_datanode_proto_rawDescData)
	})
	return file_com_datanode_proto_rawDescData
}

var file_com_datanode_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_com_datanode_proto_goTypes = []interface{}{
	(*Disponibilidad)(nil), // 0: com_datanode.Disponibilidad
	(*Chunk)(nil),          // 1: com_datanode.Chunk
	(*EstadoSubida)(nil),   // 2: com_datanode.EstadoSubida
	(*Empty)(nil),          // 3: com_datanode.Empty
	(*Id)(nil),             // 4: com_datanode.Id
}
var file_com_datanode_proto_depIdxs = []int32{
	3, // 0: com_datanode.Interacciones.Disponible:input_type -> com_datanode.Empty
	1, // 1: com_datanode.Interacciones.SubirArchivo:input_type -> com_datanode.Chunk
	4, // 2: com_datanode.Interacciones.Request:input_type -> com_datanode.Id
	0, // 3: com_datanode.Interacciones.Disponible:output_type -> com_datanode.Disponibilidad
	2, // 4: com_datanode.Interacciones.SubirArchivo:output_type -> com_datanode.EstadoSubida
	0, // 5: com_datanode.Interacciones.Request:output_type -> com_datanode.Disponibilidad
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_com_datanode_proto_init() }
func file_com_datanode_proto_init() {
	if File_com_datanode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_com_datanode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Disponibilidad); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_datanode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_datanode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstadoSubida); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_datanode_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_datanode_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_datanode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_com_datanode_proto_goTypes,
		DependencyIndexes: file_com_datanode_proto_depIdxs,
		MessageInfos:      file_com_datanode_proto_msgTypes,
	}.Build()
	File_com_datanode_proto = out.File
	file_com_datanode_proto_rawDesc = nil
	file_com_datanode_proto_goTypes = nil
	file_com_datanode_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// InteraccionesClient is the client API for Interacciones service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InteraccionesClient interface {
	Disponible(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Disponibilidad, error)
	SubirArchivo(ctx context.Context, in *Chunk, opts ...grpc.CallOption) (*EstadoSubida, error)
	Request(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Disponibilidad, error)
}

type interaccionesClient struct {
	cc grpc.ClientConnInterface
}

func NewInteraccionesClient(cc grpc.ClientConnInterface) InteraccionesClient {
	return &interaccionesClient{cc}
}

func (c *interaccionesClient) Disponible(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Disponibilidad, error) {
	out := new(Disponibilidad)
	err := c.cc.Invoke(ctx, "/com_datanode.Interacciones/Disponible", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interaccionesClient) SubirArchivo(ctx context.Context, in *Chunk, opts ...grpc.CallOption) (*EstadoSubida, error) {
	out := new(EstadoSubida)
	err := c.cc.Invoke(ctx, "/com_datanode.Interacciones/SubirArchivo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interaccionesClient) Request(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Disponibilidad, error) {
	out := new(Disponibilidad)
	err := c.cc.Invoke(ctx, "/com_datanode.Interacciones/Request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteraccionesServer is the server API for Interacciones service.
type InteraccionesServer interface {
	Disponible(context.Context, *Empty) (*Disponibilidad, error)
	SubirArchivo(context.Context, *Chunk) (*EstadoSubida, error)
	Request(context.Context, *Id) (*Disponibilidad, error)
}

// UnimplementedInteraccionesServer can be embedded to have forward compatible implementations.
type UnimplementedInteraccionesServer struct {
}

func (*UnimplementedInteraccionesServer) Disponible(context.Context, *Empty) (*Disponibilidad, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disponible not implemented")
}
func (*UnimplementedInteraccionesServer) SubirArchivo(context.Context, *Chunk) (*EstadoSubida, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubirArchivo not implemented")
}
func (*UnimplementedInteraccionesServer) Request(context.Context, *Id) (*Disponibilidad, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}

func RegisterInteraccionesServer(s *grpc.Server, srv InteraccionesServer) {
	s.RegisterService(&_Interacciones_serviceDesc, srv)
}

func _Interacciones_Disponible_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteraccionesServer).Disponible(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com_datanode.Interacciones/Disponible",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteraccionesServer).Disponible(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interacciones_SubirArchivo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Chunk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteraccionesServer).SubirArchivo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com_datanode.Interacciones/SubirArchivo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteraccionesServer).SubirArchivo(ctx, req.(*Chunk))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interacciones_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteraccionesServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com_datanode.Interacciones/Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteraccionesServer).Request(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

var _Interacciones_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com_datanode.Interacciones",
	HandlerType: (*InteraccionesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Disponible",
			Handler:    _Interacciones_Disponible_Handler,
		},
		{
			MethodName: "SubirArchivo",
			Handler:    _Interacciones_SubirArchivo_Handler,
		},
		{
			MethodName: "Request",
			Handler:    _Interacciones_Request_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "com_datanode.proto",
}
